countryApi:
  url: $(COUNTRY_API_URL?http://battuta.medunes.net/api)
  apiKey: $(COUNTRY_API_KEY?0b0d29abf4f972d48788065c47db3edb)
wikipediaApi:
  url: $(WIKIPEDIA_API_URL?https://en.wikipedia.org/api/)